spring:
  application:
    name: DEVICE-MANAGEMENT

  datasource:
    url: jdbc:mysql://localhost:3306/airtel_clone
    username: root
    password: 773726
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect