spring:
  application:
    name: AIRTEL-SECURITY

  datasource:
    url: jdbc:mysql://localhost:3306/airtel_security
    username: root
    password: 773726
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 6002

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - beans

jwt:
  secret: Q2F0c0luQm94ZXNBUkVDb29sU2VjdXJlU2VjcmV0S2V5MTIzIQ==

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG