spring:
  application:
    name: AIRTEL-SECURITY

  datasource:
    url: jdbc:mysql://localhost:3306/airtel_security
    username: root
    password: 773726
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 6002

jwt:
  secret: Q2F0c0luQm94ZXNBUkVDb29sU2VjdXJlU2VjcmV0S2V5MTIzIQ==
